name: 'Link Checker: On PR'

# **What it does**: Renders the content of every page and check all internal links on PR.
# **Why we have it**: To make sure all links connect correctly on changed files.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  merge_group:
  pull_request:

permissions:
  contents: read
  # TODO: Uncomment if we uncomment below
  # Needed for the 'trilom/file-changes-action' action
  # pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: "ubuntu-latest"
    # if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node-npm-setup

      - uses: ./.github/actions/get-docs-early-access
        if: ${{ github.repository == 'github/docs-internal' }}
        with:
          token: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}

      - name: Get the diff
        run: |
          git fetch origin main:main
          MERGE_BASE=$(git merge-base main ${{ github.sha }})
          DIFF=$(git diff --name-only $MERGE_BASE ${{ github.sha }} | tr '\n' ' ')
          echo "DIFF=$DIFF" >> $GITHUB_ENV

      - name: Link check all pages (internal links only)
        env:
          LEVEL: 'critical'
          ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_WRITEORG_PROJECT }}
          SHOULD_COMMENT: ${{ secrets.DOCS_BOT_PAT_WRITEORG_PROJECT != '' }}
          CHECK_EXTERNAL_LINKS: false
          CREATE_REPORT: false
          # Not strictly necessary bit it makes warmServer() a bit faster
          # because it only bothers with English to begin with, which
          # we're filtering on anyway once the list of all pages has
          # been loaded.
          ENABLED_LANGUAGES: en
          FAIL_ON_FLAW: true
          FILES_CHANGED: ${{ env.DIFF }}
        run: node src/links/scripts/rendered-content-link-checker.js

      - name: Upload artifact(s)
        if: ${{ always() }}
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
        with:
          name: artifacts
          path: ./artifacts
